version: "3.8"
services:
  app:
    build:
      context: ./docker-compose/phpfpm
      dockerfile: Dockerfile
      args:
        XDEBUG: '${XDEBUG:-false}'
        XDEBUG_CLIENT_PORT: '${XDEBUG_CLIENT_PORT:-9003}'
        XDEBUG_CLIENT_HOST: 'host.docker.internal'
        UID: '${WWWUSER:-1000}'
        GID: '${WWWGROUP:-1000}'
    container_name: abits-speedl-admin-app
    volumes:
      - './:/var/www/html'
    networks:
      - network_laravel

  

  nginx:
    image: nginx:1.18-alpine
    ports:
      - '${APP_PORT:-8081}:80'
    volumes:
      - './:/var/www/html'
#      - 'k2src:/var/www/html'
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    networks:
      - network_laravel

networks:
  network_laravel:
    driver: bridge